version: '3'
services:
  lb4:
    build: ./loopback4-example-todo
    ports:
      - 3000:3000
    links:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    ports:
      - 3306:3306
