version: '3'
services:
  mysql:
    image: mysql:5.7-debian
    build:
      context: .
      dockerfile: /dockerfile.mysql
    command: ["--bind-address=0.0.0.0", "--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    ports:
      - 3306:3306
    networks:
      - auth_lab_network

  lb4:
    build: ./loopback4-example-todo
    ports:
      - 3000:3000
    depends_on:
      - mysql
    networks:
      - auth_lab_network

networks:
  auth_lab_network:
